### ISSUE TITLE
Maximum call stack size exceeded when i pass the children node 

### ISSUE THREAD

**Issue by xmsz-stu** [react-hookz/deep-equal#264]
```
import { isEqualReactSimple } from '@react-hookz/deep-equal';
import { memo } from 'react';

const AppLink = memo(
  (props) => {
    return (
      <a
        {...props}
    );
  },
  isEqualReactSimple,
);

export default AppLink;

```
it will 
```
Uncaught RangeError: Maximum call stack size exceeded
    at Function.isView (<anonymous>)
    at isEqual (index.js:25:1)
    at compareObjects (comparators.js:59:1)
    at isEqual (index.js:32:1)
    at compareObjects (comparators.js:59:1)
    at isEqual (index.js:32:1)
    at compareObjects (comparators.js:59:1)
    at isEqual (index.js:32:1)
    at compareObjects (comparators.js:59:1)
    at isEqual (index.js:32:1)
```
when change to isEqualReact/isEqual same errors

when i remove isEqualReactSimple , it works
when i change to react-fast-compare/fast-deep-equal, it works

**Comment by xobotyi** [comment]
As far as I can understand you're having react component passed via props?

**Comment by xmsz-stu** [comment]
> As far as I can understand you're having react component passed via props?

Yes, I have pass some ReactNode through props, or use children to include them.
